### PR TITLE
fix issue #12

### LINKED ISSUE #12: DiscoveryDelegate possible strong reference cycle
Looks like the `DiscoveryDelegate` protocol should be a class type protocol and the delegate variable should be weak to avoid a strong reference cycle?

```
public protocol DiscoveryDelegate: class
```

```swift
public weak var delegate: DiscoveryDelegate?
```

### PR DESCRIPTION
**Pull request by weakfl**
fixes #12

### CODE REVIEW

File: GCXMulticastDNSKit/Discovery.swift [hunk 1]
```diff
@@ -90,7 +90,7 @@ public enum DiscoveryError: Int, Error {
 
 
 /// the protocol used for the delegate
-public protocol DiscoveryDelegate {
+public protocol DiscoveryDelegate: class {
```
Comment (PaulEhrhardt) [inline GCXMulticastDNSKit/Discovery.swift:93]: Where ist the benefit restricting protocol adoption to class types only? We would exclude structs from usage for example.

**Review by PaulEhrhardt — CHANGES_REQUESTED** [review]

File: GCXMulticastDNSKit/Discovery.swift (hunk 1 above)
Comment (weakfl) [reply GCXMulticastDNSKit/Discovery.swift:93]: Otherwise you can't declare the `delegate` property as weak in the `Discovery` class:
_'weak' may only be applied to class and class-bound protocol types_

Comment (PaulEhrhardt) [reply GCXMulticastDNSKit/Discovery.swift:93]: Yeah you are right.

**Review by PaulEhrhardt — APPROVED** [review]
